# general
seed: 42
script: new_infer_potential.py
name: adrn

# threading
mpi: True

# plots / output
output_path: /home/adrian/projects/streams/plots # deimos
make_plots: True
overwrite: True

potential:
    class_name: LawMajewski2010
    parameters:
        q1:
            range: [0.7, 2.]
        qz:
            range: [0.7, 2.]
        phi:
            range: [80. degree, 120. degree]
        v_halo:
            range: [100 km/s, 150 km/s]

simulation:
    # can be sgr, lm10, pal5
    source: sgr
    satellite_mass: 2.5e8 # this is specific to sgr

particles:
    N: 3
    selection_expr: tub != 0
    parameters:
        - tub
        - _X

# emcee
walkers: auto
burn_in: 0
steps: 10

# observational errors
# below: with no units specified, it's a fractional error
errors:
    global_factor: 1.
    vr: 10. km/s
    # mu_l: 1. milliarcsecond/year
    # mu_b: 1. milliarcsecond/year
    distance: 0.02