# general
seed: 42
script: infer_potential.py
name: exper1_8_8

# plots / output
plot:
    mcmc_diagnostics: True
    posterior: True
    ext: png

# data
data_file: data/observed_particles/2.5e8.hdf5
# nparticles: 4
# particle_idx: [3, 3667, 710, 1576]
nparticles: 8
particle_idx: [1244, 193, 15, 3649, 3363, 2761, 3180, 1027]

# integration
dt: -1.

potential:
    class_name: LawMajewski2010
    parameters: [q1, qz, phi, v_halo, log_R_halo]

particles:

satellite:
    parameters: [alpha]

# emcee
start_truth: True
acceptance_threshold: 0.1
walkers: 128
burn_in: 2500
steps: 25000
output_every: 1000
a: 1.7
thin_chain: False