# general
seed: 42
script: infer_potential.py
name: exper1_8_r_halo

# plots / output
plot:
    mcmc_diagnostics: True
    posterior: True
    ext: png

# data
data_file: data/observed_particles/2.5e8.hdf5
nparticles: 4
particle_idx: [3, 3667, 710, 1576]

# integration
dt: -1.

potential:
    class_name: LawMajewski2010
    parameters: [q1, qz, phi, v_halo, R_halo]

particles:

satellite:
    parameters: [alpha]

# emcee
start_truth: True
acceptance_threshold: 0.1
walkers: 128
burn_in: 2500
steps: 1000
output_every: 1000
a: 2.
thin_chain: False