# general
seed: 42
script: infer_potential.py
name: exper1_7

# plots / output
plot:
    mcmc_diagnostics: True
    posterior: True
    ext: png

# data
data_file: data/observed_particles/2.5e7.hdf5
nparticles: 8
particle_idx: [553, 1718, 1828, 1581, 384, 2305, 1695, 775]

# integration
dt: -1.

potential:
    class_name: LawMajewski2010
    parameters: [q1, qz, phi, v_halo]

particles:

satellite:
    parameters: [alpha]

# emcee
start_truth: True
walkers: 64
burn_in: 5000
burn_beta: 1.
cool_down: 0
steps: 5000
thin_chain: False