# general
seed: 42
script: infer_potential.py
name: exper3_marg_tub
# streams_path: /path/to/streams

# plots / output
plot:
    mcmc_diagnostics: True
    posterior: True
    ext: png
#output_path: /tmp

# data
data_file: data/observed_particles/2.5e8.hdf5
nparticles: 4
particle_idx: [3, 3667, 710, 1576]

# integration
dt: -1.

potential:
    class_name: LawMajewski2010
    parameters: [q1, qz, phi, v_halo]

particles:
    parameters: [d, mul, mub, vr]
    missing_dims: [mul, mub]

satellite:
    parameters: [d, mul, mub, vr, alpha]
    missing_dims: [mul, mub]

# emcee
start_truth: True
acceptance_threshold: 0.05
walkers: 256
burn_in: 2500
steps: 100000
output_every: 1000
a: 1.25
thin_chain: False