# general
seed: 42
script: infer_potential.py
name: exper3
# streams_path: /path/to/streams

# plots / output
plot:
    mcmc_diagnostics: True
    posterior: True
    ext: png
#output_path: /tmp

# data
data_file: data/observed_particles/2.5e8_N1024_DH_exp3.hdf5
nparticles: 8
particle_idx: [255, 241, 447, 339, 213, 183, 643, 530]

# integration
dt: -1.
# t1: 0
# t2: -6200.

potential:
    class_name: LawMajewski2010
    parameters: [q1, qz, phi, v_halo]

particles:
    parameters: [d, mul, mub, vr, tub]

satellite:
    parameters: [d, mul, mub, vr]

# emcee
start_truth: True
walkers: 256
burn_in: 5000
burn_beta: 1.
cool_down: 0
steps: 5000
thin_chain: False
