# general
seed: 42
script: infer_potential.py
name: exper4_marg_tub
# streams_path: /path/to/streams

# plots / output
plot:
    mcmc_diagnostics: True
    posterior: True
    ext: png
#output_path: /tmp

# data
data_file: data/observed_particles/2.5e8_exp4.hdf5
# nparticles: 4
# particle_idx: [3, 3667, 710, 1576]
nparticles: 16
particle_idx: [397, 0, 2245, 3150, 2588, 1937, 2655, 2461, 799, 2748, 1476, 910, 2433, 158, 40, 2433]

# integration
dt: -2.

potential:
    class_name: LawMajewski2010
    parameters: [q1, qz, phi, v_halo, R_halo]

particles:
    parameters: [d, mul, mub, vr]
    missing_dims: []

satellite:
    parameters: [d, mul, mub, vr, alpha]
    missing_dims: []

# emcee
start_truth: True
acceptance_threshold: 0.05
walkers: 256
burn_in: 10000
steps: 300000
output_every: 1000
a: 1.25
thin_chain: False