# general
seed: 42
script: infer_potential.py
name: exper4
# streams_path: /path/to/streams

# plots / output
plot:
    mcmc_diagnostics: True
    posterior: True
    ext: png
#output_path: /tmp

# data
data_file: data/observed_particles/2.5e8_exp4.hdf5
nparticles: 8
# particle_idx: [582, 585, 231, 300, 637, 508, 404, 1460]
# particle_idx: [60, 1283, 0, 1742, 1091, 767, 710, 147]
particle_idx: [60, 1283, 0, 1742, 1571, 767, 710, 612]

# integration
dt: -1.

potential:
    class_name: LawMajewski2010
    parameters: [q1, qz, phi, v_halo]

particles:
    parameters: [d, mul, mub, vr, tub]
    missing_dims: []

satellite:
    parameters: [d, mul, mub, vr, alpha]
    missing_dims: []

# emcee
start_truth: True
acceptance_threshold: 0.1
walkers: 256
burn_in: 5000
steps: 10000
output_every: 1000
a: 1.25
thin_chain: False