# general
seed: 42
script: infer_potential.py
name: just_potential

# threading
mpi: True
#threads: 2

# plots / output
make_plots: True
#output_path: /tmp
#output_path: /hpc/astro/users/amp2217/jobs/output_data # hotfoot
output_path: /vega/astro/users/amp2217/output_data # yeti
overwrite: True

potential:
    class_name: LawMajewski2010

data:
    class_name: SgrSimulation
    kwargs:
        mass: 2.5e8 # this is specific to sgr

particles:
    N: 25
    selection_expr: tub != 0

model_parameters:
    potential:
        q1:
            a: 1.1
            b: 1.5
        qz:
            a: 1.1
            b: 1.5
        phi:
            a: 85. degree
            b: 110. degree
        v_halo:
            a: 100 km/s
            b: 150 km/s

# emcee
walkers: 128 # or auto (2 x number of parameters)
burn_in: 0
steps: 100
