# general
seed: 42
script: new_infer_potential.py
name: adrn

# threading
mpi: no
threads: 2

# plots / output
make_plots: True
overwrite: True
output_path: /Users/adrian/projects/streams/plots # laptop

potential:
    class_name: LawMajewski2010
    parameters:
        - q1
        - qz
        - phi
        - v_halo

simulation:
    # can be sgr, lm10, pal5
    source: sgr
    satellite_mass: 2.5e8 # this is specific to sgr

particles:
    N: 2
    selection_expr: tub != 0
    parameters:
        - tub # unbinding times
        - flat_X # all true 6D positions for all particles

# emcee
walkers: auto # or auto (2 x number of parameters)
burn_in: 0
steps: 100

# observational errors
# below: with no units specified, it's a fractional error
observational_errors: true
global_error_multiple: 1.
#radial_velocity_error: 10. km/s
#proper_motion_error: 1. milliarcsecond/year
#distance_error: 0.02