# general
seed: 42
script: infer_potential.py
name: orphan_leading

# plots / output
plot:
    mcmc_diagnostics: True
    posterior: True
    ext: png

# data
data_file: data/observed_particles/orphan_leading.hdf5
nparticles: 16

# integration
dt: -1.

potential:
    class_name: LawMajewski2010
    parameters: [q1, qz, phi, v_halo]

particles:
    parameters: [d, mul, mub, vr, tub]

satellite:
    parameters: [d, mul, mub, vr, alpha, logmass]

# emcee
start_truth: False
walkers: 512
burn_in: 5000
burn_beta: 1.
cool_down: 0
steps: 0
thin_chain: False
