# general
seed: 42
name: pal5_challenge_disk_bulge

# plots / output
plot:
    mcmc_diagnostics: True
    posterior: True
    ext: png
log_level: debug

# data files
star_data: data/gaia-challenge-2/pal5/true_stars.txt
progenitor_data: data/gaia-challenge-2/pal5/true_prog.txt
nstars: 16

# integration
integration:
    dt: -1.
    nsteps: 4000

potential:
    class: GC2Pal5Potential
    parameters:
        m_halo: LogarithmicPrior(1E11, 5E12)
        Rh: LogarithmicPrior(10., 50.0)
        qz: UniformPrior(0.72, 1.3)
        m_disk: LogarithmicPrior(5E10, 5E11)
        a: UniformPrior(4,9)
        b: UniformPrior(0.1,0.5)
    fixed:
        # m_disk: 100000000000.
        # a: 6.5
        # b: 0.26
        m_spher: 34000000000.
        c: 0.7
        # Rh: 32.26
        # qz: 0.814

progenitor:
    mass: 13150.
    mass_loss_rate: 4.4625
    # mass_loss_rate: 0.

hyperparameters:
    # alpha: 1.125
    # theta: -0.3
    alpha: UniformPrior(0.7, 1.7)
    theta: UniformPrior(-2, 0)
