# general
seed: 42
name: pal5_challenge

# plots / output
plot:
    mcmc_diagnostics: True
    posterior: True
    ext: png
log_level: debug

# data files
star_data: data/gaia-challenge-2/pal5/true_stars.txt
progenitor_data: data/gaia-challenge-2/pal5/true_prog.txt
nstars: 16

# integration
integration:
    dt: -1.
    nsteps: 6000

potential:
    class: GC2Pal5Potential
    parameters:
        m_halo: LogarithmicPrior(5E11, 5E12)
        Rh: LogarithmicPrior(10., 50.0)
        qz: UniformPrior(0.72, 1.3)
    fixed:
        m_disk: 100000000000.
        a: 6.5
        b: 0.26
        m_spher: 34000000000.
        c: 0.7

progenitor:
    mass: 1.7E4
    mass_loss_rate: 3.83333

hyperparameters:
    alpha: 1.25
    theta: 0.
