# general
seed: 42
script: infer_potential.py
name: test

# plots / output
make_plots: True
output_path: /tmp
input_file: /tmp/test.hdf5
#output_path: /hpc/astro/users/amp2217/jobs/output_data # hotfoot
#output_path: /vega/astro/users/amp2217/output_data # yeti
#output_path: /Users/adrian/projects/streams/plots # laptop
#output_path: /home/adrian/projects/streams/plots # deimos

potential:
    class_name: LawMajewski2010
    parameters:
        q1:
            a: 1.1
            b: 1.5
        qz:
            a: 1.1
            b: 1.5
        phi:
            a: 85. degree
            b: 110. degree
        v_halo:
            a: 100 km/s
            b: 150 km/s

particles:
    N: 25
    selection_expr: tub != 0

        # _X:
        #     errors: # with no units specified, fractional error
        #         factor: 1. # multiplies all errors
        #         vr: 10. km/s
        #         # mu_l: 1. milliarcsecond/year
        #         # mu_b: 1. milliarcsecond/year
        #         D: 0.02
        # tub:

    # satellite:
    #     _X:
    #         errors:
    #             factor: 1. # multiplies all errors
    #             l: 1 milliarcsecond
    #             b: 1 milliarcsecond
    #             D: 0.05
    #             mul: 1.2 mas/yr
    #             mub: 1.2 mas/yr
    #             vr: 5 km/s
            # OR:
            # prior: LogUniformPrior
            # kwargs:
            # a: [-180 deg,-90 deg,10 kpc,-20 mas/yr,-20 mas/yr,-400 km/s]
            # b: [180 deg, 90 deg, 100 kpc, 20 mas/yr, 20 mas/yr, 400 km/s]

# emcee
walkers: 16 # or auto (2 x number of parameters)
burn_in: 0
steps: 100