# general
seed: 42
script: infer_potential.py
name: test

# plots / output
make_plots: True
output_path: /tmp
input_file: /tmp/test.hdf5
#output_path: /hpc/astro/users/amp2217/jobs/output_data # hotfoot
#output_path: /vega/astro/users/amp2217/output_data # yeti
#output_path: /Users/adrian/projects/streams/plots # laptop
#output_path: /home/adrian/projects/streams/plots # deimos

potential:
    class_name: LawMajewski2010
    parameters:
        q1:
            a: 1.1
            b: 1.5
        qz:
            a: 1.1
            b: 1.5
        phi:
            a: 85. degree
            b: 110. degree
        v_halo:
            a: 100 km/s
            b: 150 km/s

# integration
dt: -1.

# emcee
walkers: auto # or auto (2 x number of parameters)
burn_in: 0
steps: 10