# general
seed: 42
name: orphan

# plots / output
plot:
    mcmc_diagnostics: True
    posterior: True
    ext: png
log_level: debug

# data files
star_data: data/.../stars.txt
progenitor_data: data/.../progenitor.txt
nstars: 16 # optional

# integration
dt: -1.
nsteps: 6000

potential:
    class: LM10Potential
    parameters: [q1, qz]
    fix:
        q2: 1
        v_halo: 0.125

# emcee
nwalkers: 512
nburn_in: 5000
nsteps: 0
thin_chain: False
