# general
seed: 42
script: infer_potential.py
name: test

# plots / output
plot:
    mcmc_diagnostics: True
    posterior: True
    ext: png

# data
data_file: data/observed_particles/2.5e8.hdf5
nparticles: 2
particle_idx: [637, 508]

# integration
dt: -1.

potential:
    class_name: LawMajewski2010
    parameters: [q1, qz]

particles:
    parameters: [d, mul, mub, vr]

satellite:
    parameters: [d, mul, mub, vr, alpha]

# emcee
start_truth: True
walkers: 32
burn_in: 25
burn_beta: 1.
cool_down: 0
steps: 0
thin_chain: False