# general
seed: 42
script: infer_potential.py
name: test
# streams_path: /path/to/streams

# plots / output
plot:
    mcmc_diagnostics: False
    posterior: True
    ext: png
#output_path: /tmp

# data
data_file: data/observed_particles/2.5e8_N1024.hdf5
nparticles: 2
particle_idx: [0,512]

# integration
dt: -1.
# t1: 0
# t2: -6200.

potential:
    class_name: LawMajewski2010
    parameters: [q1, qz, phi, v_halo]

particles:
    parameters: [l,b,d,mul,mub,vr]

satellite:
    parameters: [l,b,d,mul,mub,vr,logm0]

# emcee
walkers: 46
burn_in: 5
steps: 10
iterate: 1
steps_final: 0
thin_chain: False

# satellite:
#     _X:
#         errors:
#             factor: 1. # multiplies all errors
#             l: 1 milliarcsecond
#             b: 1 milliarcsecond
#             D: 0.05
#             mul: 1.2 mas/yr
#             mub: 1.2 mas/yr
#             vr: 5 km/s
