# general
seed: 42
name: test

# plots / output
plot:
    mcmc_diagnostics: True
    posterior: True
    ext: png
log_level: debug

# data files
star_data: streams/inference/tests/true_stars.txt
progenitor_data: streams/inference/tests/true_prog.txt
# progenitor_data: streams/inference/tests/no_mass_prog.txt
nstars: 4 # optional

# integration
integration:
    dt: -1.
    nsteps: 6000

#        v_h: UniformPrior(0.25, 1.)
potential:
    class: LeeSutoNFWPotential
    parameters:
        v_h: NormalPrior(0.5, 0.1)
        r_h: LogarithmicPrior(5., 30.0)
    fixed:
        a: 1
        b: 1
        c: 1

progenitor:
    mass_range: [1E6, 5E6]
    mass_loss: 0.

hyperparameters:
    alpha: LogarithmicPrior(0.5, 3.)
    theta: -0.3

# emcee
emcee:
    nwalkers: 32
    nburn: 5000
    nsteps: 10000
    thin_chain: False
