# general
seed: 42
script: infer_potential.py
name: test

# plots / output
plot:
    mcmc_diagnostics: True
    posterior: True
    ext: png

# data
data_file: data/observed_particles/2.5e8.hdf5
nparticles: 2
particle_idx: [637, 508]

# integration
dt: -1.

potential:
    class_name: LawMajewski2010
    parameters: [q1, qz, log_R_halo]

particles:
#    parameters: [d, mul, tub]

satellite:
#    parameters: [d, mul, mub, vr, alpha]

# emcee
start_truth: True
acceptance_threshold: 0.01
walkers: 8
burn_in: 0
steps: 20
output_every: 10
thin_chain: False