# general
seed: 42
script: infer_potential.py
name: test

# plots / output
plot:
    mcmc_diagnostics: True
    posterior: True
    ext: png

K: 1000

# data
data_file: data/observed_simulation/2.5e8.hdf5
# nlead: 4
# ntrail: 4
# expr: "(tub > 1800) & (tub < 5500) & (d < 40)"
star_idx: [1084, 30418, 29467, 15733, 23613, 10333, 68481, 184]
# star_idx: [1084, 30418, 29467, 15733, 48961, 53964, 43864, 41614, 23613, 10333, 68481, 184, 932, 16417, 42214, 23800]

# integration
dt: -1.

potential:
    class_name: LM10Potential
    parameters: [qz]

progenitor:
    #parameters: [d, mul, mub, vr, alpha]
    parameters: [alpha]

stars:
    # missing_dims: []
    # fixed_truth: False

# emcee
start_truth: True
acceptance_threshold: 0.01
walkers: 32
burn_in: 0
steps: 100
output_every: 100
thin_chain: False