# general
seed: 42
name: orphan

# plots / output
plot:
    mcmc_diagnostics: True
    posterior: True
    ext: png
log_level: debug

# data files
star_data: streams/inference/tests/obs_stars.txt
progenitor_data: streams/inference/tests/true_prog.txt
nstars: 16 # optional

# integration
integration:
    dt: -1.
    nsteps: 6000

potential:
    class: LM10Potential
    parameters: [q1, qz]
    fixed:
        q2: 1
        v_halo: 0.125

# emcee
emcee:
    nwalkers: 32
    nburn: 5000
    nsteps: 10000
    thin_chain: False
