# general
seed: 42
script: infer_potential.py
name: test

# plots / output
plot:
    mcmc_diagnostics: True
    posterior: True
    ext: png

# data
data_file: data/observed_particles/2.5e8.hdf5
nparticles: 2

# integration
dt: -1.

potential:
    class_name: LawMajewski2010
    parameters: [q1, qz, phi, v_halo]

particles:
    parameters: [d, mul, mub, vr]
    missing_dims: []

satellite:
    parameters: [d, mul, mub, vr]
    missing_dims: []

# emcee
start_truth: True
walkers: 36
burn_in: 10
burn_beta: 1.
cool_down: 0
steps: 10
thin_chain: False