# general
seed: 42
script: infer_potential.py
name: test
# streams_path: /path/to/streams

# plots / output
plot:
    mcmc_diagnostics: True
    posterior: False
    ext: png
#output_path: /tmp

# data
data_file: data/observed_particles/2.5e8_N1024.hdf5
nparticles: 8

# integration
dt: -1.
# t1: 0
# t2: -6200.

potential:
    class_name: LawMajewski2010
    parameters: [q1, qz, phi, v_halo]

particles:
#    parameters: [d]
#    parameters: [l, b, d, mul, mub, vr]

satellite:
    parameters: [d, mul, mub, logmass]

# TODO: logm0

# priors should be
#    l - uniform in cos(l)
#    b - uniform in cos(b)
#    d - uniform
#    mul - uniform
#    mub - uniform
#    vr - uniform

# emcee
walkers: 24
burn_in: 100
burn_beta: 0.01
cool_down: 20
steps: 100
thin_chain: False

# satellite:
#     _X:
#         errors:
#             factor: 1. # multiplies all errors
#             l: 1 milliarcsecond
#             b: 1 milliarcsecond
#             D: 0.05
#             mul: 1.2 mas/yr
#             mub: 1.2 mas/yr
#             vr: 5 km/s
