# general
seed: 42
script: new_infer_potential.py
name: adrn

# threading
mpi: false
#threads: 2

# plots / output
make_plots: false
output_path: /tmp
#output_path: /hpc/astro/users/amp2217/jobs/output_data # hotfoot

potential:
    class_name: LawMajewski2010

data:
    class_name: SgrSimulation
    kwargs:
        mass: 2.5e8 # this is specific to sgr

particles:
    N: 25
    selection_expr: tub != 0

model_parameters:
    potential:
        q1:
            a: 0.7
            b: 2.
        qz:
            a: 0.7
            b: 2.
        phi:
            a: 80. degree
            b: 120. degree
        v_halo:
            a: 100 km/s
            b: 150 km/s

# emcee
walkers: 16 # or auto (2 x number of parameters)
burn_in: 0
steps: 5
